### ISSUE TITLE
Add the Repo to the Awesome Nix List (& the Nix Community Org)

### ISSUE THREAD

**Issue by Melkor333** [musnix/musnix#101]
Hey Guys!

I've just seen that this repo isn't visible in either the [awesome nix list](https://nix-community.github.io/awesome-nix/), nor is it part of the [Nix Community Organisation](https://github.com/nix-community/) (which I both just discovered via [discourse](https://discourse.nixos.org/t/discover-the-nix-community-github-org/3675/2) :grin: ).
I'm not using musnix at moment, but I had good experience with it and I think it is a valuable project for the community!

Would you mind if I create a PR to add it to the awesome nix list?

Also, I personally think that it would be nice to move this repo directly in the nix community org so that it becomes a bit easier to discover. But that's up to you I guess. :)

**Comment by magnetophon** [comment]
Sounds great to me, but I think you should wait for @henrytill 's opinion, since he's by far the most active in here.
Personally I didn't know any of these sites and repos, so thanks for pointing them out!

**Comment by henrytill** [comment]
> Would you mind if I create a PR to add it to the awesome nix list?

That would be great.  Much appreciated @Melkor333!

**Comment by Melkor333** [comment]
It's now in the list :)

**Comment by henrytill** [comment]
Awesome.  Thanks again @Melkor333.
