### ISSUE TITLE
attribute 'linuxPackages_4_9_rt' missing

### ISSUE THREAD

**Issue by egasimus** [musnix/musnix#104]
This is what I get when trying to enable `musnix` from a fresh checkout; same if trying to add it via `nix-channel`:

```
building Nix...
building the system configuration...
error: while evaluating the attribute 'activationScript' of the derivation 'nixos-system-machine-01-19.09.2036.c49da6435f3' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:102:5:
while evaluating the attribute 'system.activationScripts.script' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/activation-script.nix:68:9:
while evaluating 'textClosureMap' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/strings-with-deps.nix:70:35, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/activation-script.nix:89:18:
while evaluating 'id' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/trivial.nix:14:5, called from undefined position:
while evaluating the attribute 'text' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/activation-script.nix:9:5:
while evaluating the attribute 'text' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/strings-with-deps.nix:77:38:
while evaluating the attribute 'sources' of the derivation 'etc' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/etc.nix:12:5:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/etc.nix:20:20, called from undefined position:
while evaluating the attribute 'source' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:336:9:
while evaluating the option `environment.etc.fish/generated_completions.source':
while evaluating the attribute 'mergedValue' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:368:5:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:368:32, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:368:19:
while evaluating 'check' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/types.nix:245:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:369:10:
while evaluating the attribute 'passAsFile' of the derivation 'system_fish-completions' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'package' of the derivation 'nixos-manpages_fish-completions' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'buildCommand' of the derivation 'nixos-manpages' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'buildCommand' of the derivation 'manual-olinkdb' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'buildCommand' of the derivation 'nixos-manual-combined' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'buildCommand' of the derivation 'generated-docbook' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'buildCommand' of the derivation 'options-docbook.xml' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating 'substFunction' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/nixos/lib/make-options-doc/default.nix:28:19, called from /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/nixos/lib/make-options-doc/default.nix:37:54:
while evaluating the attribute 'default' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/lib/options.nix:154:44:
while evaluating 'scrubOptionValue' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/lib/options.nix:173:22, called from /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/lib/options.nix:154:54:
while evaluating 'isDerivation' at /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/lib/attrsets.nix:305:18, called from /nix/store/dih2w8m7yw2qp6zl89k8aar1lndjk2m3-nixos-19.09.2036.c49da6435f3/nixos/lib/options.nix:174:8:
while evaluating the attribute 'default' at /etc/nixos/musnix/modules/kernel.nix:84:7:
attribute 'linuxPackages_4_9_rt' missing, at /etc/nixos/musnix/modules/kernel.nix:84:17
```

**Comment by evanjs** [comment]
Also experiencing this, be it with pinned musnix or `nix-channel`
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.13, NixOS, 20.09pre218482.3320a06049f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre218482.3320a06049f"`
 - channels(evanjs): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

As such, I am currently unable to build with a RT PREEMPT kernel.

Note that disabling realtime does allow me to build using both nixops and morph.

<details>
<summary>content of sources.json</summary>

``` json
{
    "musnix": {
        "branch": "master",
        "description": "Real-time audio in NixOS",
        "homepage": "",
        "owner": "musnix",
        "repo": "musnix",
        "rev": "c8294030b2d13f13f6cd98f0e77b2d01df9a1a7d",
        "sha256": "09gsrchfvf4080kwaxczc6g78p2r07xidp3z2f7miq2v2s7yivm5",
        "type": "tarball",
        "url": "https://github.com/musnix/musnix/archive/c8294030b2d13f13f6cd98f0e77b2d01df9a1a7d.tar.gz",
        "url_template": "https://github.com/<owner>/<repo>/archive/<rev>.tar.gz"
    },
    "niv": {
        "branch": "master",
        "description": "Easy dependency management for Nix projects",
        "homepage": "https://github.com/nmattia/niv",
        "owner": "nmattia",
        "repo": "niv",
        "rev": "372f96bff217a7a019de27667d04118cffa9841b",
        "sha256": "1l0z6162zw60pdcdj03aq64qgf1vyzmf24i9pxca64i4sprl1b7p",
        "type": "tarball",
        "url": "https://github.com/nmattia/niv/archive/372f96bff217a7a019de27667d04118cffa9841b.tar.gz",
        "url_template": "https://github.com/<owner>/<repo>/archive/<rev>.tar.gz"
    },
    "nixpkgs": {
        "branch": "nixos-unstable",
        "description": "A read-only mirror of NixOS/nixpkgs tracking the released channels. Send issues and PRs to",
        "homepage": "https://github.com/NixOS/nixpkgs",
        "owner": "NixOS",
        "repo": "nixpkgs-channels",
        "rev": "3320a06049fc259e87a2bd98f4cd42f15f746b96",
        "sha256": "1g5l186d5xh187vdcpfsz1ff8s749949c1pclvzfkylpar09ldkl",
        "type": "tarball",
        "url": "https://github.com/NixOS/nixpkgs-channels/archive/3320a06049fc259e87a2bd98f4cd42f15f746b96.tar.gz",
        "url_template": "https://github.com/<owner>/<repo>/archive/<rev>.tar.gz"
    }
}
```

</details>

**Comment by evanjs** [comment]
It looks like I still get this error after pulling in #107.

I wonder if @magnetophon or others have thoughts on why this might be happening.

**Comment by evanjs** [comment]
Soooo I was finally able to build (still using #107) with `linuxPackages_4_19_rt`.
I think the problem I was having is that I wasn't properly importing `config`,`pkgs`, and etc. all the way down, so I would never get the full overridden `linuxPackage` set from `musnix`.

AFAIK, this is a more noticeable issue with morph, nixops, and basically _anything_ that involves building for other systems, I think?

This isn't a concern when you're using musnix for a local system, as long as you have `config` and etc imported in the top level of your configs.

Maybe a basic config for nixops or such would be a good item to include in the examples? 
Or even a comment noting extra care might be required when deploying like this.
But this is one of those cases where I wonder if it belongs in the docs for the project, or if the user should know that going into this, to begin with  :man_shrugging:

**Comment by egasimus** [comment]
>But this is one of those cases where I wonder if it belongs in the docs for the project, or if the user should know that going into this, to begin with 

This is one of those cases where one wonders if the Nix way _can_ be made more discoverable at all, or it's just one of these things where you have to grok it by trial and error.

For reference, my `configuration.nix` does starts with `{ config, options, pkgs, lib, ... }: with pkgs;`.  Maybe I should pass some of these arguments down to Musnix though? With something like `callPackage` which is... probably documented somewhere?

I've never tried Musnix on anything else but local NixOS, and as far as my intuition tells me (only doing Nix for a few months though) what you said shouldn't make any differrence - but it could? Or maybe it's working for you now because something changed in Nix(OS) upstream?

I'm really confused about the root cause of this issue and also about the lack of response from Musnix maintainers.

**Comment by magnetophon** [comment]
@evanjs 
> Maybe a basic config for nixops or such would be a good item to include in the examples?

Yes please! Can you provide them?

@egasimus 

>I'm really confused about the root cause of this issue and also about the lack of response from Musnix maintainers.

Sorry for the lack of response.
I don't know the cause, nor how to troubleshoot, so I didn't want to reply with a hollow message.

**Comment by egasimus** [comment]
@magnetophon That's understandable. We're all in this together!

Last time I looked, it seemed like some sort of circular reference issue. `pkgs.linuxPackages_4_9_rt` is used here:

https://github.com/musnix/musnix/blob/373040af1df246c64dc70f2ae49a16b59e1ad936/modules/kernel.nix#L84

but at that point `pkgs` has no such attribute; it is only added via applying the package overrides that start here:

https://github.com/musnix/musnix/blob/373040af1df246c64dc70f2ae49a16b59e1ad936/modules/kernel.nix#L113

That was as far as I got. Since then, I've had a few more sessions of writing Nix and trying to get random things to run on my system. I just looked at that file some more, and here are my thoughts:

* Maybe, like @evanjs suggested, there's some external factor that alters the order in which these are evaluated, and it's only under some condition X that the overrides are actually applied before `mkOption` being called?
* Maybe Nix cares about the order of argument expansion, e.g. `{ options, config, ... }` is not the same as `{ config, options, ... }`?
* Maybe there's a way to make sure the package overrides are always applied prior to parsing the option definitions? After all, wouldn't one expect the `_rt` packages to exist when Musnix is added, even if they're not enabled via `kernel.realtime = true`?

**Comment by OctavioElMagnifico** [comment]
Hi! I'm suffering the same bug and pretty much blocked as I had to do some braking changes into my system configuration and now I can't adequate my musnix generations.

This is what I get, mo matter what kernel I choose or if I try with this git repo or with the channel.

`error: attribute 'kernel' missing, at /home/paquetesNix/musnix/modules/kernel.nix:10:35
(use '--show-trace' to show detailed location information)
`

This is the trace.

[realTimeKernelTrace.txt](https://github.com/musnix/musnix/files/4742458/realTimeKernelTrace.txt)

**Comment by henrytill** [comment]
> This is what I get, mo matter what kernel I choose or if I try with this git repo or with the channel.
> 
> `error: attribute 'kernel' missing, at /home/paquetesNix/musnix/modules/kernel.nix:10:35 (use '--show-trace' to show detailed location information) `
> 

@OctavioElMagnifico: this particular problem came up recently (see #108), and I believe we have a fix in `master` for it.

**Comment by OctavioElMagnifico** [comment]
That's great. I was also chasing possible solutions, there is a breaking modification on nix syntax, was it related to that change?

**Comment by henrytill** [comment]
Thanks for the lead there @OctavioElMagnifico, I will have a closer look to see if that might be affecting us.

@magnetophon are you using 20.03 or unstable?

**Comment by magnetophon** [comment]
I use unstable.

**Comment by egasimus** [comment]
Quick question: is evaluation of the Nix language itself deterministic? Maybe the circular reference doesn't manifest for everyone because of some Heisenbug in the Nix interpreter or builder?

**Comment by henrytill** [comment]
> Quick question: is evaluation of the Nix language itself deterministic? Maybe the circular reference doesn't manifest for everyone because of some Heisenbug in the Nix interpreter or builder?

@egasimus: AFAIK it is, I've never seen any non-determinism of this sort.

**Comment by henrytill** [comment]
@OctavioElMagnifico: #124 should have fixed building on 20.03.  Lemme know if it works for you.

**Comment by OctavioElMagnifico** [comment]
Thank you, @henrytill ! I'm compiling right now, everything seems fine.

**Comment by magnetophon** [comment]
The 4 series kernels are no longer in musnix.
