### ISSUE TITLE
The 3.14 RT Kernel does not work with BTRFS

### ISSUE THREAD

**Issue by thorhop** [musnix/musnix#12]
I discovered this when staring at the boot sequence for a while and googling my way to a certain error (which I can't remember at the time and my logs are written to a BTRFS file system... which it didn't do because it was sputtering out write errors left and right -- so,yeeeah - the logs currently contain no traces of the RT kernel related errors). I think we should either find another version of the kernel patch that supports both ***RT*** and ***BTRFS*** or add a checking hook for both ```musnix.kernel.realtime``` and ```musnix.kernel.optimize``` (unless it's the stdKernel?)  to see if the **configuration.nix** or **hardware-configuration.nix** contains any ```fileSystems.*.fsType = "btrfs;"``` to fail the rebuild process and notify the user of the incompatibility.

**Comment by thorhop** [comment]
NOTE: Setting ```musnix.kernel.optimize = true;``` does not break boot. So it's the **RT patch** that breaks **BTRFS**.

**Comment by thorhop** [comment]
Arch Wiki confirms this
https://wiki.archlinux.org/index.php/Btrfs#Linux-rt_kernel

**Comment by cillianderoiste** [comment]
My system also fails to boot with the musnix.kernel.realtime option enabled because it fails to load the module for the XFS filesystem I use. With `musnix.kernel.optimize = true;` I can boot successfully.

**Comment by magnetophon** [comment]
http://www.spinics.net/lists/linux-rt-users/msg13096.html confirms that 3.14_rt does not work with btrfs, but also says 3.18_rt is OK.
@kmicu will test 4.08 wit btrfs.
