### ISSUE TITLE
Add flake to musnix

### ISSUE THREAD

**Issue by Narice** [musnix/musnix#125]
Adding a flake to musnix would make it possible to use it in a pure nixos system, adding the channel would not be necessary if using the flake which would be really usefull for reproducability and ease of deployement.

**Comment by andyrichardson** [comment]
Flake support would be great and #134 looks to be a great start.

In the meantime, you can still use it with a flake "polyfill".

```nix
# flake.nix
{
  inputs = {
    musnix = {
      url = "github:musnix/musnix";
      flake = false;
    };
    flake-compat = {
      url = "github:edolstra/flake-compat";
      flake = false;
    };
  };
}
```
```nix
# configuration.nix
{ inputs, ... }:
{
  imports = [ "${inputs.musnix}/default.nix" ];
  musnix.enable = true;
}
```

**Comment by Narice** [comment]
Thanks for your comment!

**Comment by cidkidnix** [comment]
If you could test the branch from my repo, and report back in the MR saying that it works fine it would be appreciated.

**Comment by Narice** [comment]
it works and it's great :+1:!

**Comment by Narice** [comment]
as PR #134 was merged, this issue should be closed!
thanks @cidkidnix!
