### ISSUE TITLE
Support home-manager plugin paths

### ISSUE THREAD

**Issue by bandithedoge** [musnix/musnix#137]
Musnix currently sets plugin path environment variables for plugins either declared in `environment.systemPackages` or installed through `nix-env`, but not plugins declared in home-manager's `home.packages`. For example, LV2 plugins installed that way are stored in `/nix/var/nix/profiles/per-user/<user>/home-manager/home-path/lib/lv2` and `/etc/profiles/per-user/<user>/lib/lv2/`.

**Comment by henrytill** [comment]
No objection here.  I don't use home manager myself, so PRs welcome!
