### ISSUE TITLE
Unable to run `nix-env -u` with musnix installed

### ISSUE THREAD

**Issue by RobbieGM** [musnix/musnix#138]
Hi, thanks so much for this package! I'd like your help on something that I think is an issue with musnix.
Running `nix-env -u` to update my user-specific packages causes this output:

    error: anonymous function at /nix/store/zxw18d1pmvla0283k28xgn2hayi4f81h-musnix/musnix/default.nix:1:1 called without required argument 'config'

The contents of that file are the same as those [here](https://github.com/musnix/musnix/blob/master/default.nix). I followed [these instructions](https://github.com/musnix/musnix#using-musnix-as-a-channel) to install musnix and I'm on NixOS 22.0.5. Let me know if you need any more information to recreate the issue.

**Comment by magnetophon** [comment]
I am not able to reproduce this on NixOS unstable.

**Comment by RobbieGM** [comment]
Huh. Do you know how I should troubleshoot it?

**Comment by magnetophon** [comment]
I don't know the proper way to debug this, sorry.

Just brainstorming:
You already determined that if you uninstall musnix, the problem goes away, right?
You could try to install musnix in one of the other two methods.
You could also try to uninstall packages until the issue goes away, to at least pinpoint which pkg is at fault.

**Comment by RobbieGM** [comment]
I tried uninstalling musnix. I actually couldn't get the problem to go away until I also removed the <musnix> channel. Then I was able to update my packages and add musnix back (hopefully? I have yet to see if it will break after updating the other stuff).

**Comment by RobbieGM** [comment]
Looks like musnix is working fine after the update/reinstall. Though nix-env -u is still not working.

**Comment by magnetophon** [comment]
@RobbieGM Is this still an issue?

**Comment by RobbieGM** [comment]
These days I'm using `nix profile upgrade '.*'` instead of `nix-env -u` and the former works, so I guess it's not really an issue anymore.
