### ISSUE TITLE
pkgs.linuxPackages_latest_rt fails to build on current unstable

### ISSUE THREAD

**Issue by fps** [musnix/musnix#140]
<pre>
In file included from ../include/asm-generic/bug.h:5,
                 from ../arch/x86/include/asm/bug.h:83,
                 from ../include/linux/bug.h:5,
                 from ../drivers/net/ethernet/netronome/nfp/bpf/jit.c:6:
In function 'ur_load_imm_any',
    inlined from 'jeq_imm' at ../drivers/net/ethernet/netronome/nfp/bpf/jit.c:3146:13:
../include/linux/compiler.h:350:45: error: call to '__compiletime_assert_722' declared with attribute error: FIELD_FIT: value too large for the field
  350 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |                                             ^
../include/linux/compiler.h:331:25: note: in definition of macro '__compiletime_assert'
  331 |                         prefix ## suffix();                             \
      |                         ^~~~~~
../include/linux/compiler.h:350:9: note: in expansion of macro '_compiletime_assert'
  350 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
../include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
../include/linux/bitfield.h:49:17: note: in expansion of macro 'BUILD_BUG_ON_MSG'
   49 |                 BUILD_BUG_ON_MSG(__builtin_constant_p(_val) ?           \
      |                 ^~~~~~~~~~~~~~~~
../include/linux/bitfield.h:67:17: note: in expansion of macro '__BF_FIELD_CHECK'
   67 |                 __BF_FIELD_CHECK(_mask, 0ULL, _val, "FIELD_FIT: ");     \
      |                 ^~~~~~~~~~~~~~~~
../drivers/net/ethernet/netronome/nfp/bpf/jit.c:653:13: note: in expansion of macro 'FIELD_FIT'
  653 |         if (FIELD_FIT(UR_REG_IMM_MAX, imm))
      |             ^~~~~~~~~

</pre>

**Comment by fps** [comment]
<pre>
[root@nixos:~]# nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
[root@nixos:~]# cat .nix-defexpr/channels/nixos/.git-revision 
2da64a81275b68fdad38af669afeda43d401e94b
</pre>

**Comment by dag-h** [comment]
Can confirm that this still happens on nixpkgs unstable [#37bd39839acf99c5b738319f42478296f827f274](https://github.com/NixOS/nixpkgs/commit/37bd39839acf99c5b738319f42478296f827f274)

**Comment by fps** [comment]
You might try one of the kernels added in this PR: https://github.com/musnix/musnix/pull/144

**Comment by dag-h** [comment]
I tried with the 5.16 kernel and it built successfully. Although I still can't get RT scheduling to work with jack through pipewire. Do you know if this should work out of the box with `musnix.enable = true` and `musnix.kernel.realtime = true`?

**Comment by fps** [comment]
Is your user part of the <code>audio</code> group? 

What error message do you get from jack?

**Comment by dag-h** [comment]
Yes I'm part of the `audio` group.

I get errors from the client using jack saying it failed to set real time priority. It tries to use `jack_acquire_real_time_scheduling` but receives a non-zero return value.

**Comment by fps** [comment]
Ok, show me the output of the command:

<pre>$ groups</pre>

And also the contents of the limits.conf file pointed to by <code>/etc/pam.d/systemd-user</code>. In my case it looks like this:

<pre>
$ cat /etc/pam.d/systemd-user
# Account management.
account required pam_unix.so

# Authentication management.
auth sufficient pam_unix.so   likeauth try_first_pass
auth required pam_deny.so

# Password management.
password sufficient pam_unix.so nullok sha512

# Session management.
session required pam_env.so conffile=/etc/pam/environment readenv=0
session required pam_unix.so
session required pam_loginuid.so
session optional /nix/store/hhwkvh589y34p6znr2rcv28zw9afjccj-systemd-251.4/lib/security/pam_systemd.so
session required /nix/store/bb996xyb7vmbgjl0nch03dyk7mywpgx9-linux-pam-1.5.2/lib/security/pam_limits.so conf=/nix/store/4js76c9qsn38l0ahl13d1qsb3xl7bf8m-limits.conf
</pre>

And the file pointed to:
<pre>
$ cat /nix/store/4js76c9qsn38l0ahl13d1qsb3xl7bf8m-limits.conf
@audio - memlock unlimited
@audio - rtprio 99
@audio soft nofile 99999
@audio hard nofile 99999
@jackaudio - rtprio 99
@jackaudio - memlock unlimited
</pre>

**Comment by dag-h** [comment]
```shell
$ groups
users wheel audio networkmanager wireshark adbusers
```

```shell
# Account management.
account required pam_unix.so

# Authentication management.
auth sufficient pam_unix.so   likeauth try_first_pass
auth required pam_deny.so

# Password management.
password sufficient pam_unix.so nullok sha512

# Session management.
session required pam_env.so conffile=/etc/pam/environment readenv=0
session required pam_unix.so
session required pam_loginuid.so
session optional /nix/store/wv5321690mvbf1da065dg53h7drcdl9z-systemd-251.4/lib/security/pam_systemd.so
session required /nix/store/xlj08vfj9qzw2ynwxki60jvzzn2hlj1i-linux-pam-1.5.2/lib/security/pam_limits.so conf=/nix/store/9vaqn2mywmq7smgsjs53lgxwlz0g3wvm-limits.conf
```

```shell
@audio - memlock unlimited
@audio - rtprio 99
@audio soft nofile 99999
@audio hard nofile 99999
```

Only difference seems to be the `@jackaudio` entries, but I think the `jackaudio` group is just another equivalent for the `audio` group right?

Thanks a lot for helping out!

**Comment by fps** [comment]
The <code>jackaudio</code>  group is used when running jack as a service, which I gathered from your comments is not what you do. Or do you? How do you run jack?

**Comment by dag-h** [comment]
Yes, I'm using the `services.pipewire.jack` module. Unfortunate! Appreciate your help regardless.

**Comment by fps** [comment]
I guess you need to tell pipewire to enable rt-scheduling. But I'm just guessing..

https://docs.pipewire.org/page_module_rt.html

and maybe

<code>services.pipewire.config.client-rt</code>

**Comment by dag-h** [comment]
Had a chat in the pipewire irc. For PW setups, the `pipewire` group should be used, and not the `audio` group. The entries in limits.conf should also be a bit different. See https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Performance-tuning#rlimits

Also, the pipewire implementation of `jack_acquire_real_time_scheduling` had a fallback dummy implementation since it doesn't take a jack client as an argument. This is likely the main cause of the issue. This was immediately fixed by a maintainer.

Although, a real time kernel is probably not a good match for PW setups, according to a maintainer. They said it would likely have an impact on performance. Might just try configuring my system without `musnix` for now!

**Comment by magnetophon** [comment]
How come an rt kernel is not a good match for pipewire?
I'm assuming the goal is to have reliable audio without xruns and you are willing to sacrifice some performance in other areas.

**Comment by dag-h** [comment]
Not sure! That's just what the pipewire maintainer told me. We were talking specifically about jack and real time priority, so I would assume they understood what the broad goal was. I'm trying to use a jack client that requires RT scheduling. I'm new to the linux audio space, and the audio space in general, so I'm not entirely sure what I need. Music production is the application anyway!

**Comment by magnetophon** [comment]
Maybe you should ask that maintainer again, and make it explicit that you want reliable audio first and everything else is less important.
As far as I know, the only way to guarantee a specific application or set of applications gets real time priority, is to use an rt kernel.
