### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ocharles** [musnix/musnix#147]
I just wanted to pop in and say a big thank you for putting this together! For years I've had guitarix but could never get the tuner to work due to lack of real-time audio. I dropped this module and loe and behold - I have a working guitar tuner! If you release another NixOS module that actually makes me good at guitar, let me know :sweat_smile: 

Thanks!

**Comment by henrytill** [comment]
On behalf of my co-maintainer @magnetophon and all of our wonderful contributors, you're welcome @ocharles!  Thanks for the kind words, they are much appreciated.

As per the other thing, still looking myself... :laughing:

**Comment by magnetophon** [comment]
Does anyone know any software that  will make me a good singer and drummer?   :)
