### ISSUE TITLE
Unable to build linux-5.19.0-rt10 on unstable anymore.

### ISSUE THREAD

**Issue by magnetophon** [musnix/musnix#151]
I get:
```
  LD [M]  drivers/gpu/drm/amd/amdgpu/amdgpu.o
  AR      drivers/gpu/built-in.a
  AR      drivers/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: warning: arch/x86/power/hibernate_asm_64.o: missing .note.GNU-stack section implies executable stack
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  CC      .vmlinux.export.o
  LD      .tmp_vmlinux.btf
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: warning: arch/x86/power/hibernate_asm_64.o: missing .note.GNU-stack section implies executable stack
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: warning: .tmp_vmlinux.btf has a LOAD segment with RWX permissions
  BTF     .btf.vmlinux.bin.o
  LD      .tmp_vmlinux.kallsyms1
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: warning: .btf.vmlinux.bin.o: missing .note.GNU-stack section implies executable stack
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: warning: .tmp_vmlinux.kallsyms1 has a LOAD segment with RWX permissions
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: warning: .btf.vmlinux.bin.o: missing .note.GNU-stack section implies executable stack
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: warning: .tmp_vmlinux.kallsyms2 has a LOAD segment with RWX permissions
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      vmlinux
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: warning: .btf.vmlinux.bin.o: missing .note.GNU-stack section implies executable stack
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: warning: vmlinux has a LOAD segment with RWX permissions
  BTFIDS  vmlinux
FAILED: load BTF from vmlinux: Invalid argument
make: *** [../Makefile:1164: vmlinux] Error 255
make: *** Deleting file 'vmlinux'
error: build of '/nix/store/h43jnc9lzq1mrn287dymrvfcx0wpbi8j-linux-5.19.0-rt10.drv' on 'ssh://nixBuild@builder' failed: builder for '/nix/store/h43jnc9lzq1mrn287dymrvfcx0wpbi8j-linux-5.19.0-rt10.drv' failed with exit code 2;
```

**Comment by magnetophon** [comment]
I tried all kernels in musnix, and only got 5.4 to compile.

**Comment by henrytill** [comment]
Possibly related to https://github.com/NixOS/nixpkgs/pull/194551?

**Comment by henrytill** [comment]
I have the sneaking suspicion that some kernel updates are in order after [the recent update of `pahole`](https://github.com/NixOS/nixpkgs/commit/69df0f15ccd720f4f51e045eb924816b87c6fa37).  I'm checking `5.15.76-rt53`, as the `5.15` series is the most recent [longterm release](https://www.kernel.org/category/releases.html).

The `5.10` realtime kernel in nixpkgs is also building after a [recent bump](https://github.com/NixOS/nixpkgs/commit/5bcbe8ecd1c7f551ddeb850a4e6f28f942457a0b).

**Comment by henrytill** [comment]
Moving forward, we might consider a policy of only keeping a couple of updated longterm release kernels and the latest kernel (which we need to package, as its currently `6.0.5-rt14`).

Seems like some pruning is in order nonetheless.

**Comment by henrytill** [comment]
After #152 and #154 merge, I will remove `5.6`,`5.9`, `5.16`, `5.17`, and `5.19`.

**Comment by magnetophon** [comment]
Why do we need to prune kernels?

**Comment by henrytill** [comment]
> Why do we need to prune kernels?

They're broken :laughing:

But more seriously, if you start to inspect the affected [branches](https://cdn.kernel.org/pub/linux/kernel/projects/rt/), it doesn't look like they are receiving realtime patch updates.  `5.17` hasn't seen an updated realtime patch update since April, `5.16` since January, etc..  

This is why I'm suggesting we go with the longtime release kernels and newer ones - they are getting the necessary updates to avoid this breakage.  The newest `5.15`, `5.10`, and `5.4` patches all build without failure after the `pahole` update.

**Comment by henrytill** [comment]
> This is why I'm suggesting we go with the longtime release kernels and newer ones - they are getting the necessary updates to avoid this breakage. The newest `5.15`, `5.10`, and `5.4` patches all build without failure after the `pahole` update.

In case I wasn't clear, the longterm release patches _are_ getting realtime patch updates AFAICT.

**Comment by magnetophon** [comment]
Gotcha, makes perfect sense!

**Comment by henrytill** [comment]
Alright, we have lived to fight another day!
