### ISSUE TITLE
latest kernel

### ISSUE THREAD

**Issue by Pitometsu** [musnix/musnix#25]
There maybe should be `pkgs.linuxPackages_latest_rt` version.

**Comment by henrytill** [comment]
This seems reasonable to me.

So, as of now, `pkgs.linuxPackages_latest_rt` would be assigned to `pkgs.linuxPackages_4_1_rt`, and, in the future, would always be assigned to the latest version of the realtime kernel packages.  

Does this sound like what you are envisioning?

**Comment by Pitometsu** [comment]
@henrytill yes, right, thanks!
