### ISSUE TITLE
custom kernel modules

### ISSUE THREAD

**Issue by Pitometsu** [musnix/musnix#26]
On vanilla default NixOS kernel brightness work just fine. But it not work with
```nix
  musnix = {
    enable = true;
    kernel = {
      packages = pkgs.linuxPackages_4_1_rt;
    };
  };
```
NixOS on `ThinkPad-T440p`.
Currently I have:
```nix
  boot = {
    extraModprobeConfig = ''
      # thinkpad acpi
      options thinkpad_acpi fan_control=1
      # intel graphics
      options i915 modeset=1 i915_enable_rc6=7 i915_enable_fbc=1 lvds_downclock=1 powersave=0
      # intel audio
      options snd-hda-intel index=0 id=PCH
      options snd-hda-intel index=1 id=HDMI
      # fix intel wifi-N
      options iwlwifi 11n_disable=1
    '';
    extraModulePackages = [ config.boot.kernelPackages.tp_smapi ];
    kernelParams = [
      "acpi_osi="
      "video.use_native_backlight=1"
      "pcie_aspm=force"
      "drm_kms_helper.edid_firmware=edid/1920x1080.bin"
      "video=1920x1080"
      "clocksource=acpi_pm pci=use_crs"
      "consoleblank=0"
    ];
    loader.gummiboot.enable = true;
    loader.efi.canTouchEfiVariables = true;
    initrd.kernelModules = [
      "intel_agp"
      "i915"
      "bbswitch"
      # jack
      "snd-aloop"
    ];
    blacklistedKernelModules = [
      # No beeping
      "snd_pcsp"
      "pcspkr"
      # fix bumblebee
      "nvidia_uvm"
      # because of intel
      "nouveau"
      "nvidia"
      "nvidiafb"
      # buggy and old
      "thinkpad_acpi"
    ];
  };
```
What can be cause of the issue?

**Comment by henrytill** [comment]
I need some clarification in order to understand the problem.  

When you say that it doesn't work, does this mean you are not able to build and switch to the real-time kernel with your current configuration?  Or does it mean that you are able to build and switch to the real-time kernel, but something related to setting the brightness of your display isn't working for you correctly.

**Comment by Pitometsu** [comment]
The second case.

**Comment by Pitometsu** [comment]
So should I somehow extra-ordinal customize modules for this rt kernel?

**Comment by henrytill** [comment]
There's no separate or special handling of kernel modules in musnix itself, and both my intuition and experience suggest that those NixOS configuration options would work as expected.

That said, I've only tested it on machines with no additional kernel configuration beyond what was auto-generated by `nixos-generate-config` and provided by musnix, so I don't really have any experience with the specific settings you've used here.

Is it only the brightness issue, or are some of the other parts of your configuration also not working?

**Comment by henrytill** [comment]
@Pitometsu: Do you need any more assistance on this?  Is it okay if I close this?

**Comment by Pitometsu** [comment]
@henrytill issue no more reproduce on 6655ea0d4deb6f9b216aeb1ccf56faecdc4c1655, master. Thanks.
