### ISSUE TITLE
setpci: command not found

### ISSUE THREAD

**Issue by nico202** [musnix/musnix#28]
Hi, I'm on the unstable branch. The only thing I needed to edit before getting it working was replacing pksg.ffado with pkgs.ffadoFull.
However, I noticed at boot that it says "setpci: command not found". Don't know how to fix (pciutils is in my pkgs)

Thanks for your (wonderful) work

edit: relevant config
```
  musnix = {
    enable = true;
    ffado.enable = true;
    kernel = {
      optimize = true;
      realtime = true;
      packages = pkgs.linuxPackages_4_4_rt;
    };
    rtirq = {
      enable = true;
      nameList = "firewire_ohci";
    };
    soundcardPciId = "01:09.0";
    das_watchdog.enable = false;
  };
```

**Comment by henrytill** [comment]
Thanks for the report!

I've pushed a possible fix for the `setpci` issue in c211724 and updated `pkgs.ffado` to `pkgs.ffadoFull` in da5b07f.  Could you pull, rebuild, and let me know how it goes?

**Comment by nico202** [comment]
Both fixed, thanks!

**Comment by henrytill** [comment]
Excellent!
