### ISSUE TITLE
New to NixOS but willing to put in the effort.

### ISSUE THREAD

**Issue by erlandsona** [musnix/musnix#31]
I dual booted my 2010 MBP with Arch. pacman -Pqsnvuwhateveretc... to upgrade my system after realizing I needed the linux-rt kernel to do any sort of useful audio work in Linux. Of course my system effectively fell apart.

So a few months later and a bit more into learning Haskell, buying a new laptop for a bigger cpu, I'm deciding I want to utilize the benefits of NixOS. Granted I keep throwing my test VM's into kernel panics / SEG_FAULTs (lol).

The docs are great for getting KDE up and running like no problem but here's the system I'm trying to build...

 - linux-rt kernel    (for realtime audio)
 - vim
 - xmonad             (Also still need to figure out how to configure the windowing commands to behave like my TMUX setup...)
 - haskell               (platform / tools)
 - some sort of network manager / widget (network-manager or similar)
 - chrome / firefox (for netflix)
 - spotify
 - Bitwig / Ableton / Renoise

Maybe a file browser just for my lady in case she needs to get anything done with it? But I'll probably just save my MBP for her to play with.

Any help or guidance would be so greatly appreciated! Thanks!

**Comment by erlandsona** [comment]
UPDATE: I'm past the kernel panics / SEGFAULTS to the best of my knowledge. I've got a super basic XMonad, vim, chromium, setup, and I'm working on integrating Musnix to get the Realtime stuff setup. Granted this is all from inside a VM for now till I actually get my new box in.

**Comment by magnetophon** [comment]
Everything on that list should be doable, or even relatively easy.

The only exceptions is Ableton. No idea if it even runs under wine or so, and NixOS is gonna be an extra barrier.

**Comment by erlandsona** [comment]
Question, So I'm starting to get the gist of things but at some point you still need other config files for some of the programs you install with Nix... Ala: .xmonad/xmonad.hs file, .vimrc, and .bash_profile's. What's a best practice for having Nix be responsible for those config file as well? Or do I still have to manually manage those in a git repo and symlink them after all the nix stuff?

**Comment by magnetophon** [comment]
Tough one; there is no best practice really.
Here's [some examples](https://nixos.org/wiki/Real_World_NixOS_Dotfiles) of how others do it.

There's also people working on dedicated programs for this, but afaik nothing finished.

The problem is that dotfiles ned to be RW to work, and the nix store needs to be read-only.

**Comment by erlandsona** [comment]
Thanks a ton! RE: dotfiles RW: That makes sense. Thanks for the link. I'm exploring now, but it sounds like I'll be able to use a Nix installation to make just getting the default environment / system up and running but configuration of individual programs will still have to be done manually.

**Comment by erlandsona** [comment]
Okay so I've read into pretty much all the examples but I'm not seeing a decent command or function or expression for cloning GH repo's? I've tried reading the nixpkgs docs but I just get lost every time I dig into them.
