### ISSUE TITLE
Dead link for realtime patch

### ISSUE THREAD

**Issue by pngwjpgh** [musnix/musnix#32]
`https://www.kernel.org/pub/linux/kernel/projects/rt/4.6/patch-4.6.5-rt9.patch.xz` lives at `https://www.kernel.org/pub/linux/kernel/projects/rt/4.6/older/patch-4.6.5-rt9.patch.xz`.

Should I open a pull request bumping the version to the more current `4.6.7-rt11`?

---

For now a workaround is to say:
`nix-prefetch-url "https://www.kernel.org/pub/linux/kernel/projects/rt/4.6/older/patch-4.6.5-rt9.patch.xz"`.

**Comment by henrytill** [comment]
Hi @pngwjpgh, thanks for letting me know.  Indeed, I've fallen behind updates recently, so a PR bumping to `4.6.7-rt11` is more than welcome! 

You can refer to bee3a3a for an example of this type of update.

**Comment by magnetophon** [comment]
@henrytill 
>  I've fallen behind on updates recently

musnix is one of the most up to date rt kernel repo's out there.
Many thanks for that!

**Comment by henrytill** [comment]
@magnetophon: glad to hear it!  

It'd be great to automate the update process.
