### ISSUE TITLE
Tracking kernel-related changes in nixos-unstable

### ISSUE THREAD

**Issue by henrytill** [musnix/musnix#39]
https://github.com/musnix/musnix/compare/unstable

**Comment by erlandsona** [comment]
This sounds like it might fix my issue as well... I'm trying to use the nixos-unstable channel and I can't run a rebuild switch. I'm getting this error...

```
# nixos-rebuild switch --upgrade
downloading Nix expressions from ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.03pre97792.c311871/nixexprs.tar.xz’...
downloading ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.03pre97792.c311871/nixexprs.tar.xz’... [7999/8858 KiB, 7995.6 KiB/s]
unpacking channels...
building Nix...
building the system configuration...
error: attempt to call something which is not a function but a set, at /home/erlandsona/musnix/modules/kernel.nix:162:49
(use ‘--show-trace’ to show detailed location information)
```

**Comment by henrytill** [comment]
Yes, it could very well be the same problem.  You could try checking out the `unstable` branch and rebuilding from that.

**Comment by henrytill** [comment]
Definitely time to rebase this branch against `master`...

**Comment by henrytill** [comment]
Annnnd rebased:
https://github.com/musnix/musnix/compare/unstable

**Comment by magnetophon** [comment]
I was having the same issue as @erlandsona, and can confirm this fixes it.

**Comment by erlandsona** [comment]
I'm assuming this isn't getting merged until 17 is the stable channel eh?

**Comment by henrytill** [comment]
> I'm assuming this isn't getting merged until 17 is the stable channel eh?

That was my original intent, though it would be good to find an avenue for keeping things compatible with `-16.09` (and below?).  Maintaining separate git branches is less than ideal, but certainly a possibility...
