### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by magnetophon** [musnix/musnix#4]
Do some testing, like:
https://github.com/rockfabrik/deployment/blob/master/tests/mixing.nix

This one plays some sweeps and makes a spectogram, which we should copy, and indexes the music library, which might not be applicable.

Did I miss anything it does?

Other tests could be to record and play sounds at various latencies and channel counts and document when xruns start to occur, but that probably doesn't make sense in a VM.

Anything else we should do?

**Comment by henrytill** [comment]
I've started work on this here:
https://github.com/musnix/musnix/tree/topic/tests

**Comment by magnetophon** [comment]
Great!

**Comment by henrytill** [comment]
I think it's safe to say that after the work by @mcdonc in #173 and #176 we can close this out.  We now have something approaching a reasonable CI, though we might consider if it's feasible to test more than just default RT kernel in the future.

**Comment by magnetophon** [comment]
Wow, didn't realize we started musnix almost 10 years ago!

**Comment by henrytill** [comment]
Indeed, 10 years this December! :confetti_ball:
