### ISSUE TITLE
CONFIG_HPET_TIMER is already set to Y

### ISSUE THREAD

**Issue by peterhoeg** [musnix/musnix#41]
In regular nixos-unstable:

``` shell
$ zgrep HPET /proc/config.gz
CONFIG_HPET_TIMER=y
CONFIG_HPET_EMULATE_RTC=y
CONFIG_HPET=y
```

No point setting it again.

**Comment by henrytill** [comment]
Thanks, that's good to know.  I wonder how long this has been true...

I'll check to see if it's enabled on a stock `nixos-16.09` system.

**Comment by peterhoeg** [comment]
It's the same on 16.09 - just checked.

**Comment by henrytill** [comment]
You beat me to it!

I wonder if it's safe to assume that people using musnix are all on `-16.09` or `-unstable` at this point.

cc @magnetophon - thoughts?

**Comment by magnetophon** [comment]
Personally I'm trying to upgrade from ''16.09'' to ''unstable'', but is there a real downside to just leaving it be a bit longer for those who haven't?

**Comment by henrytill** [comment]
> is there a real downside to just leaving it be a bit longer for those who haven't?

I can't think of any.  @peterhoeg - any objections?

> Personally I'm trying to upgrade from ''16.09'' to ''unstable''.

Seen #39?

**Comment by peterhoeg** [comment]
None at all.

**Comment by henrytill** [comment]
It's probably safe to make this change, now that #42 has been merged.
