### ISSUE TITLE
cannot build an rt kernel with 17.09

### ISSUE THREAD

**Issue by magnetophon** [musnix/musnix#43]
When I try to nixos-rebuild with ``kernel.realtime `` enabled, I get:
```
error: anonymous function at /home/bart/source/nixpkgs/pkgs/os-specific/linux/kernel/generic.nix:1:1 called without required argument ‘hostPlatform’, at /home/bart/source/musnix/pkgs/os-specific/linux/kernel/linux-4.9-rt.nix:3:1
```

**Comment by magnetophon** [comment]
Seems like I just need to add ``hostPlatform, `` to the 1st line of each linux.nix, and we're good again.
I guess we need an ``unstable`` branch again, huh?

**Comment by erlandsona** [comment]
@magnetophon I'm finally back to updating my system again and just ran into this as well...

**Comment by magnetophon** [comment]
I built a kernel with the ``hostPlatform,`` mod on 17.03, and it seems to build just fine there too.
So it seems we don't need a separate branch after all.

**Comment by erlandsona** [comment]
@magnetophon can you paste an example here? What does the `hostPlatform` mod look like?

**Comment by magnetophon** [comment]
@erlandsona Just change the first line of ``linux-4.9-rt.nix`` (or whatever version you're using) to:
```
{ stdenv, hostPlatform, fetchurl, perl, buildLinux, ... } @ args:
```

**Comment by erlandsona** [comment]
Thanks!

**Comment by henrytill** [comment]
> I built a kernel with the hostPlatform, mod on 17.03, and it seems to build just fine there too.
> So it seems we don't need a separate branch after all.

That's great to hear.  Feel free to push your changes!

**Comment by henrytill** [comment]
Whoops didn't mean to close...

**Comment by henrytill** [comment]
Are we ready to close this?

**Comment by magnetophon** [comment]
Yes.
