### ISSUE TITLE
RT kernel breaks adding undetected screen resolution in nixos-unstable

### ISSUE THREAD

**Issue by magnetophon** [musnix/musnix#44]
## Issue description

I have some hardware where the correct screen resolution is not detected.
I've been able to work around that by doing:
```
xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
xrandr --addmode VGA-0 1920x1080_60.00
xrandr --output VGA-0 --mode 1920x1080_60.00
```
After an upgrade to nixos-unstable, that leads to a screen where the image is too high up, and cut off on the right.
IOW: the bottom and right side of my screen are black.

The issue [goes away](https://github.com/NixOS/nixpkgs/issues/27168#issuecomment-313486140) when using a non-rt kernel.

This might very well be an upstream issue, but I don't know how to find out.

PS) for testing I made ``Linux compnix 4.9.35-rt25 #1-NixOS SMP PREEMPT RT Thu Jun 29 11:00:49 UTC 2017 x86_64 GNU/Linux``, if you want I can do a PR.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.09pre110213.01c3847b9c (Hummingbird)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.11
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.09pre110213.01c3847b9c"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
build-use-sandbox = true

**Comment by magnetophon** [comment]
Any news on this?
How do I tell if the issue is upstream or not?

**Comment by henrytill** [comment]
I could never repro this.  I'm guessing this was an upstream problem.

Close?

**Comment by magnetophon** [comment]
I've closed it for now, also since I haven't used the affected mashine in a while, and won't do so in the near future.
