### ISSUE TITLE
boot.kernelPackages = pkgs.linuxPackages_latest; prevents building an rt kernel

### ISSUE THREAD

**Issue by magnetophon** [musnix/musnix#55]
If the configuration.nix contains ``boot.kernelPackages = pkgs.linuxPackages_latest;``, then the rt kernel will not build, without producing an error.
``nixos-rebuild test`` will just go trough the motions, and without building a new kernel, it will finish with ``the following new units were started: ``, indicating the rebuild was successful.

Oddly enough, https://github.com/musnix/musnix/blob/master/modules/kernel.nix#L143 does get called, cause when you change the ``13`` to nonsense, you get an error.
Even weirder: when you change ``callPackage`` in that line to nonsense, the rebuild will just claim to finish.

Maybe relevant: I also have: ``musnix.kernel.packages = pkgs.linuxPackages_latest_rt;``

**Comment by henrytill** [comment]
As discussed over in `#musnix`, I'm not that surprised given that we are setting `boot.kernelPackages` here: https://github.com/musnix/musnix/blob/master/modules/kernel.nix#L100-L103

That said, it would seem to me that having a conflicting override that is silently ignored is the wrong behavior.

Then again, moving these kernels to nixpkgs will also solve this problem..

**Comment by magnetophon** [comment]
OK, thanks.
