### ISSUE TITLE
Failure during kernel rebuild

### ISSUE THREAD

**Issue by akamaus** [musnix/musnix#57]
On nixos-17.09 after setting

> musnix.enable = true;
> musnix.kernel.realtime = true;

> sudo  -E nixos-rebuild boot

```
...
GOT: *
QUESTION: CRC-CCITT functions, NAME: CRC_CCITT, ALTS: M/y/?, ANSWER: 
GOT: 
QUESTION: CRC16 functions, NAME: CRC16, ALTS: M/y/?, ANSWER: 
GOT: 
GOT: CRC calculation for the T10 Data Integrity Field (CRC_T10DIF) [Y/?] y
QUESTION: CRC ITU-T V.41 functions, NAME: CRC_ITU_T, ALTS: M/y/?, ANSWER: 
GOT: 
GOT: CRC32/CRC32c functions (CRC32) [Y/?] y
QUESTION:   CRC32 perform self test on init, NAME: CRC32_SELFTEST, ALTS: N/y/?, ANSWER: n
GOT: 
GOT:   CRC32 implementation
GOT:   > 1. Slice by 8 bytes (CRC32_SLICEBY8)
GOT:     2. Slice by 4 bytes (CRC32_SLICEBY4)
GOT:     3. Sarwate's Algorithm (one byte at a time) (CRC32_SARWATE)
GOT:     4. Classic Algorithm (one bit at a time) (CRC32_BIT)
CHOICE: 1-4?, ANSWER: 
QUESTION: CRC7 functions, NAME: CRC7, ALTS: M/y/?, ANSWER: 
GOT: 
QUESTION: CRC32c (Castagnoli, et al) Cyclic Redundancy-Check, NAME: LIBCRC32C, ALTS: M/y/?, ANSWER: 
GOT: 
QUESTION: CRC8 function, NAME: CRC8, ALTS: M/y/?, ANSWER: 
GOT: 
QUESTION: PRNG perform self test on init, NAME: RANDOM32_SELFTEST, ALTS: N/y/?, ANSWER: 
GOT: 
GOT: XZ decompression support (XZ_DEC) [Y/?] y
QUESTION: XZ decompressor tester, NAME: XZ_DEC_TEST, ALTS: N/m/y/?, ANSWER: n
GOT: 
QUESTION: glob self-test on init, NAME: GLOB_SELFTEST, ALTS: N/y/?, ANSWER: n
GOT: 
QUESTION: CORDIC algorithm, NAME: CORDIC, ALTS: M/y/?, ANSWER: 
GOT: 
QUESTION: JEDEC DDR data, NAME: DDR, ALTS: N/y/?, ANSWER: 
GOT: 
GOT: IRQ polling library (IRQ_POLL) [Y/?] y
QUESTION: Select compiled-in fonts, NAME: FONTS, ALTS: N/y/?, ANSWER: 
GOT: 
GOT: #
GOT: # configuration written to .config
GOT: #
GOT: make[1]: Leaving directory '/tmp/nix-build-linux-config-4.9.35-rt25.drv-0/build'
GOT: make: Leaving directory '/tmp/nix-build-linux-config-4.9.35-rt25.drv-0/linux-4.9.35'
error: unused option: RT_GROUP_SCHED
builder for ‘/nix/store/kdjqqv28kdvjxya5ffmsrc2cz5yq7n7a-linux-config-4.9.35-rt25.drv’ failed with exit code 255
```

**Comment by henrytill** [comment]
Curious.  I'll see if I can reproduce locally...

`nixos-version`?

**Comment by akamaus** [comment]
% nixos-version                                                                                                                          
17.09.git.0e423ee (Hummingbird)

it was forked from channels/nixos-17.09 at commit 1987983 and cotains some innoncent stuff not related to kernel at all.

**Comment by henrytill** [comment]
Okay, I can reproduce here on `17.09.2281.b4a0c011e81 (Hummingbird)` (aka latest `17.09`).

I'll investigate a fix.

**Comment by henrytill** [comment]
Fix: https://github.com/musnix/musnix/pull/58

Let me know if this works for you.

**Comment by akamaus** [comment]
Sort of works. At least kernel compiled successfully. But later compilation process stopped on nvidia module saying it doesn't support PREEMPT_RT. Looks like I have to stop now, because I can't sacrifice the ability to run cuda. Thanks for your help.

**Comment by erlandsona** [comment]
So maybe I'm missing something here, but I'm trying to build the latest kernel with NixOS 17.09 and the NVidia drivers which I'm reading after running into said PREEMPT_RT error that there are some patches necessary to the kernel?/nvidia drivers? to get the nvidia drivers to play nice with a real-time OS? Is that correct?

I'd really like to be able to get 4k@60hz working with my system for development and for more screen real estate on the timeline in my daw's.

**Comment by henrytill** [comment]
@erlandsona - I don't have any Nvidia hardware, so I'm afraid I won't be of much help, but do let me know if you find a patch or set of patches and we can go about trying to get them integrated into musnix.

**Comment by akamaus** [comment]
@erlandsona @henrytill That's surprising, but looks like people do run nvidia driver on rt-kernel. 
I found this thread https://devtalk.nvidia.com/default/topic/777636/simply-impossible-to-use-an-nvidia-card-on-a-real-time-kernel-no-musician-can-use-nvidia-/

It refers to https://aur.archlinux.org/packages/nvidia-rt/ 
Strangely, I don't see any patch code in this packet. Looks like it just works as is or close to it.
