### ISSUE TITLE
nix-env -qaP stops working

### ISSUE THREAD

**Issue by milnet2** [musnix/musnix#67]
Hi,

when I add the musinx-channel, I get the following error:
```
# nix-env -qaP
error: cannot auto-call a function that has an argument without a default value (‘config’)
```

**Comment by henrytill** [comment]
Interesting.  

I must to confess that I don't have `musnix` as a channel locally, so I haven't had a chance to test this approach myself.  It was a change we added in https://github.com/musnix/musnix/commit/7c01dc4142e98502c905abf90cc322c9d19051e5.

I will go ahead and see if I can track down the problem.  

cc @yegortimoshenko - any ideas?

**Comment by milnet2** [comment]
Thanks for picking that up Henry,

the usage as outlined in the README.md actually works pretty well. Please excuse my brevity in the last post. Thank you for providing us with musnix.

Regards
Tobias

**Comment by henrytill** [comment]
You're welcome!  Your post was quite helpful, however brief 😎 .

**Comment by henrytill** [comment]
Okay, I can reproduce this over here.  

@milnet2: what do you get from `nixos-version`?

**Comment by milnet2** [comment]
```
$ nixos-version 
17.09.3008.c831224528c (Hummingbird)
```

**Comment by smashedtoatoms** [comment]
Hey @henrytill, I am getting this as well.  

```
$ nix-env -qaP
error: cannot auto-call a function that has an argument without a default value (‘config’)
$ nixos-version
17.09.3205.12512f25e9e (Hummingbird)
```

**Comment by henrytill** [comment]
I've added a [`pre-18.03`](https://github.com/musnix/musnix/tree/pre-18.03) branch to address problems with compatibility on `master`.  

You can update your channel and try using that branch.  If you have any issues, don't hesitate to open a new ticket.
