### ISSUE TITLE
Power Management Defined Multiple Times

### ISSUE THREAD

**Issue by drewofdoom** [musnix/musnix#75]
Trying to build with `musnix.enable = true` results in the following error:

> error: The unique option `powerManagement.cpuFreqGovernor' is defined multiple times, in `/nix/store/yqhdlix4bbdbs8i3qv481a507pvmqcq8-musnix/musnix/modules/base.nix' and `/etc/nixos/hardware-configuration.nix'.

NixOS sets the governor to performance by default in recent versions.

**Comment by magnetophon** [comment]
Are you sure that it's NixOS that sets it?
A search [comes up empty](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=cpuFreqGovernor&type=).

**Comment by aij** [comment]
Older versions of `nixos-generate-config` add

      powerManagement.cpuFreqGovernor = "powersave";

in `hardware-configuration.nix`. Newer versions use `lib.mkDefault`, so  they shouldn't conflict. That was changed in dab7ecc0542c024f9725216edfbddefafc910413 so it may only be in unstable and 18.03.
