### ISSUE TITLE
Include realTimeConfigQuickScan.pl as a part of Musnix(-starter)

### ISSUE THREAD

**Issue by thorhop** [musnix/musnix#9]
Hey there! Yeeeaaah...

Spent the morning of sunday trying to get perl/Tk to build - it did, but little did I realise that the GUI version is still unstable -- and I forgot to test run realTimeConfigQuickScan.pl initially. It works!

I was introduced to realTimeConfigQuickScan.pl through Arch Linux. What it does is check the system for certain settings and outputs a list of good or bad values. As it stands I'm not 100% sure if it outputs correctly. or if it even gives us a set of system settings we want to use. Here's what it gave me and I have musnix-starter.nix imported from /etc/nixos/configuration.nix.

```
== GUI-enabled checks ==
Checking if you are root... no - good
Checking filesystem 'noatime' parameter... 3.18.3 kernel - good
(relatime is default since 2.6.30)
Checking CPU Governors... CPU 0: 'performance' CPU 1: 'performance' CPU 2: 'performance' CPU 3: 'performance' CPU 4: 'performance' CPU 5: 'performance' CPU 6: 'performance' CPU 7: 'performance'  - good
warning: '/sbin/sysctl vm.swappiness' did not produce a parsable result
Checking swappiness...  - warning
Checking for resource-intensive background processes... none found - good
Checking checking sysctl inotify max_user_watches... < 524288 - not good
increase max_user_watches by adding 'fs.inotify.max_user_watches = 524288' to /etc/sysctl.conf and rebooting
For more information, see http://wiki.linuxaudio.org/wiki/system_configuration#sysctlconf
Checking access to the high precision event timer... readable - good
Checking access to the real-time clock... readable - good
Checking whether you're in the 'audio' group... yes - good
Checking for multiple 'audio' groups... no - good
Checking the ability to prioritize processes with chrt... yes - good
Checking kernel support for high resolution timers... found - good
Kernel with Real-Time Preemption... not found - not good
Kernel without real-time capabilities found
For more information, see http://wiki.linuxaudio.org/wiki/system_configuration#installing_a_real-time_kernel
Checking if kernel system timer is set to 1000 hz... found - good
Checking kernel support for tickless timer... found - good
== Other checks ==
Checking filesystem types... 
** Warning: do not use /run/media/thor/Storage for audio files.
   fuseblk is not a good filesystem type for realtime use and large files.
   For more information, see http://wiki.linuxaudio.org/wiki/system_configuration#filesystems
not found.
** Warning: no tmpfs partition mounted on /tmp
   For more information, see:
   - http://wiki.linuxaudio.org/wiki/system_configuration#tmpfs
   - http://lowlatency.linuxaudio.org
** Set $SOUND_CARD_IRQ to the IRQ of your soundcard to enable more checks.
   Find your sound card's IRQ by looking at '/proc/interrupts' and lspci
```
So why include it in musnix and not nixpkgs? Well it might be usefull for setting up video workstations as well, but it's fairly obvious that this script checks for audio related settings. On top of that there is no build process what so ever. You only need Perl to be able to run it.

Perhaps it could be a musnix module?

Source:
https://github.com/raboof/realtimeconfigquickscan

**Comment by magnetophon** [comment]
Hi NixThor (I guess),

Thanks for the reminder. I've been using this for years, it's great.
I'm not really convinced this shouldn't be in nixpkgs though.
I would propose to put it in there, and maybe import it here.

**Comment by magnetophon** [comment]
Hi NixThor (I guess),

Thanks for the reminder. I've been using this for years, it's great.
I'm not really convinced this shouldn't be in nixpkgs though.
I would propose to put it in there, and maybe import it here.

**Comment by magnetophon** [comment]
Hi NixThor (I guess),

Thanks for the reminder. I've been using this for years, it's great.
I'm not really convinced this shouldn't be in nixpkgs though.
I would propose to put it in there, and maybe import it here.

**Comment by magnetophon** [comment]
Hi NixThor (I guess),

Thanks for the reminder. I've been using this for years, it's great.
I'm not really convinced this shouldn't be in nixpkgs though.
I would propose to put it in there, and maybe import it here.

**Comment by magnetophon** [comment]
Hi NixThor (I guess),

Thanks for the reminder. I've been using this for years, it's great.
I'm not really convinced this shouldn't be in nixpkgs though.
I would propose to put it in there, and maybe import it here.

**Comment by magnetophon** [comment]
Hi NixThor (I guess),

Thanks for the reminder. I've been using this for years, it's great.
I'm not really convinced this shouldn't be in nixpkgs though.
I would propose to put it in there, and maybe import it here.

**Comment by henrytill** [comment]
I agree that it belongs in [nixpkgs](https://github.com/NixOS/nixpkgs).

In terms of whether or not the output is accurate: if indeed you are just importing the current `musnix-starter.nix` into your configuration without changing any musnix settings, and you have rebuilt and rebooted your system, it should be reporting that you have a kernel with real-time preemption and real-time capabilities.  So this script might be making assumptions about the system which don't apply to NixOS, and would need to be patched to give accurate results.
 
If you do decide to submit it to [nixpkgs](https://github.com/NixOS/nixpkgs), we can include it in [musnix-starter](http://github.com/musnix/musnix-starter).

Okay to close?

**Comment by thorhop** [comment]
@magnetophon Cheers. It's pretty cool just as a checklist. If we import it as a module we can modify it to output stuff like machine readable outputs :D :dancer: 

@henrytill My problem was originally tied with the fact that I called a linuxPackage AFTER importing musnix, so you can kind of guess that the musnix kernel was ignored in favour of the vanilla kernel. So the script didn't fail; it really didn't find a kernel with PREEMPT.

Other than that I had to change the **SwappinessCheck.pm** file to call "**sysctl**" rather than "**/sbin/sysctl**". I've made an issue on the github page for *realTimeConfigQuickScan*, but again: it's not hard to patch.

What can I say? It's out of my hands. Do you want it as a sub-module or not? If not I could always try and package it :)

**Comment by magnetophon** [comment]
@thorhop In case you're still waiting for an answer: It would be great if you pkg it for upstream!
